In [2]:
import numpy as np

## shape

In [3]:
list1 = [1,2,3,4]
a = np.array(list1)
print(a.shape)
b = np.array([[1,2,3],[4,5,6]])

(4,)


In [4]:
print(b.shape)

(2, 3)


In [5]:
print(b[0,0])

1


## Array function

In [6]:
# fill all array component as '0'
a = np.zeros((2,2))
print(a)

[[0. 0.]
 [0. 0.]]


In [7]:
# fill all array coponents as '1'
a = np.ones((2,3))
print(a)

[[1. 1. 1.]
 [1. 1. 1.]]


In [8]:
# fill all array components as user defined number
a = np.full((2,3),5)
print(a)

[[5 5 5]
 [5 5 5]]


In [9]:
# cross
a = np.eye(3)
print(a)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [12]:
a = np.array(range(20)).reshape((4,5))
b = np.array(range(20))
print("a : ", a)
print("b : " , b)

a :  [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
b :  [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


## Slicing

In [13]:
lst = [
    [1,2,3],
    [4,5,6],
    [7,8,9],
]

# 신기한 배열 슬라이싱
arr = np.array(lst)
a = arr[0:2, 0:2]
print(a)

a = arr[1:, 1:]
print(a)

[[1 2]
 [4 5]]
[[5 6]
 [8 9]]


## Integer Indexing

In [5]:
lst = [
    [1,2,3,4],
    [5,6,7,8],
    [9,10,11,12]
]

In [6]:
a = np.array(lst)
s = a[[0,2], [1,3]]
print(s)

[ 2 12]


## Boolean Indexing

In [7]:
lst = [
    [1,2,3],
    [4,5,6],
    [7,8,9]
]

In [8]:
a = np.array(lst)

In [10]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [11]:
lst

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]