In [1]:
import numpy as np

In [4]:
arr3 = np.arange(5)
arr3

array([0, 1, 2, 3, 4])

In [5]:
# 합, 최소값
[arr3.sum(), arr3.mean()]

[10, 2.0]

In [6]:
[arr3.std(), arr3.var()]

[1.4142135623730951, 2.0]

In [12]:
A = np.array([0,1,2,3]).reshape(2,2)
A

array([[0, 1],
       [2, 3]])

In [13]:
B = np.array([3,2,0,1]).reshape(2,2)
B

array([[3, 2],
       [0, 1]])

In [15]:
# 행렬 곱
A.dot(B)

array([[0, 1],
       [6, 7]])

In [17]:
# 전치 행렬
np.transpose(A)

array([[0, 2],
       [1, 3]])