# NumPy Module

In [1]:
import numpy as np

## 통계 연산 예제

In [6]:
arr3 = np.arange(3)
print(arr3)

[0 1 2]


In [7]:
arr3.sum()

3

In [9]:
arr3.mean()

1.0

In [10]:
arr3.std()

0.816496580927726

In [11]:
arr3.var()

0.6666666666666666

## numpy 행렬 연산 예제

In [14]:
A = np.array([0,1,2,3]).reshape(2,2)
print(A)

[[0 1]
 [2 3]]


In [15]:
B = np.array([3,2,0,1]).reshape(2,2)
B

array([[3, 2],
       [0, 1]])

In [17]:
# 행렬 곱
A.dot(B)

array([[0, 1],
       [6, 7]])

In [18]:
np.transpose(A)

array([[0, 2],
       [1, 3]])