# Numpy Example 2

In [1]:
import numpy as np

## Integer indexing

In [11]:
lst = [
    [1,2,3,4],
    [5,6,7,8],
    [9,10,11,12]
]
a = np.array(lst)
s = a[[0,2], [1,3]]
print(s)

[ 2 12]


## Boolean indexing

In [14]:
lst = [
    [1,2,3],
    [4,5,6],
    [7,8,9]
]
a = np.array(lst)

In [15]:
bool_indexing_array = np.array([
    [False, True, False],
    [True, False, True],
    [False, True, False]
])
n = a[bool_indexing_array]
print(n)

[2 4 6 8]


## Array Operation 1

In [16]:

a = np.array([1,2,3])
b = np.array([4,5,6])

In [19]:
c = a+b
# c = np.add(a,b)
print(c)

[5 7 9]


In [21]:
c = np.subtract(a,b)
# c = a-b
print(c)

[-3 -3 -3]


In [22]:
c = np.multiply(a,b)
# c = a * b
print(c)

[ 4 10 18]


In [23]:
c = np.divide(a,b)
# c = a / b
print(c)

[0.25 0.4  0.5 ]
