# Numpy module Example

### shape

In [3]:
import numpy as np

In [5]:
list1 = [1,2,3,4]

a = np.array(list1)
print(a)

[1 2 3 4]


In [7]:
b = np.array([[1,2,3],[4,5,6]])
print(b.shape)
print(b[0,0])

(2, 3)
1


### array funciton

In [8]:
a = np.zeros((2,2))
print(a)

[[0. 0.]
 [0. 0.]]


In [9]:
a = np.ones((2,3))
print(a)

[[1. 1. 1.]
 [1. 1. 1.]]


In [10]:
a = np.full((2,3),5)
print(a)

[[5 5 5]
 [5 5 5]]


In [11]:
a = np.eye(3)
print(a)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [12]:
a = np.array(range(20)).reshape((4,5))

In [13]:
print(a)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


### slicing

In [14]:
lst = [
    [1,2,3],
    [4,5,6],
    [7,8,9]
]

arr = np.array(lst)

a = arr[0:2, 0:2]
print(a)

[[1 2]
 [4 5]]


### Integer indexing

In [19]:
lst = [
    [1,2,3,4],
    [5,6,7,8],
    [9,10,11,12]
]


a = np.array(lst)

a = a[[0, 2], [1,3]]

print(a)

[ 2 12]


In [20]:
lst = [
    [1,2,3],
    [4,5,6],
    [7,8,9]
]

a = np.array(lst)

bool_indexing_list = np.array([
    [False, True, False],
    [True, False, True],
    [False, True, False]
])

n = a[bool_indexing_list]
print(n)

[2 4 6 8]


In [24]:
a = np.array([1,2,3])
b = np.array([4,5,6])

c = np.divide(a,b)

print(c)

[0.25 0.4  0.5 ]


In [31]:
lst1 = [
    [1,2],
    [3,4]
]

lst2 = [
    [5,6],
    [7,8]
]

a = np.array(lst1)
b = np.array(lst2)

c = np.dot(a,b)
print(c)

[[19 22]
 [43 50]]


In [32]:
a = np.array([[1,2],[3,4]])
s = np.sum(a)

In [33]:
print(s)

10


In [34]:
s = np.sum(a, axis=1)

In [35]:
print(s)

[3 7]


In [36]:
s = np.sum(a, axis=0)
print(s)

[4 6]


In [37]:
s = np.prod(a)
print(s)

24
