# Numpy module Example

### shape

In [3]:
import numpy as np

In [5]:
list1 = [1,2,3,4]

a = np.array(list1)
print(a)

[1 2 3 4]


In [7]:
b = np.array([[1,2,3],[4,5,6]])
print(b.shape)
print(b[0,0])

(2, 3)
1


### array funciton

In [8]:
a = np.zeros((2,2))
print(a)

[[0. 0.]
 [0. 0.]]


In [9]:
a = np.ones((2,3))
print(a)

[[1. 1. 1.]
 [1. 1. 1.]]


In [10]:
a = np.full((2,3),5)
print(a)

[[5 5 5]
 [5 5 5]]


In [11]:
a = np.eye(3)
print(a)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [12]:
a = np.array(range(20)).reshape((4,5))

In [13]:
print(a)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


### slicing

In [14]:
lst = [
    [1,2,3],
    [4,5,6],
    [7,8,9]
]

arr = np.array(lst)

a = arr[0:2, 0:2]
print(a)

[[1 2]
 [4 5]]
