In [1]:
import numpy as np

In [5]:
data = [[1,2,3,4],
       [5,6,7,8]]

a = np.array(data)
print(a.shape)

(2, 4)


In [6]:
b = np.array([[1,2,3],[4,5,6]])
print(b.shape)

(2, 3)


In [7]:
print(b[0,0])

1


In [10]:
a = np.zeros((2,2))
print(a)

[[0. 0.]
 [0. 0.]]


In [11]:
b = np.ones((2,2))
print(b)

[[1. 1.]
 [1. 1.]]


In [12]:
b = np.ones((1,2))
print(b)

[[1. 1.]]


In [13]:
c = np.arange(20).reshape((4,5))

In [14]:
print(c)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [15]:
a = np.array([[1,2],[3,4]])
s = np.sum(a)
print(s)

10


In [16]:
s = np.sum(a, axis=1)

In [17]:
print(s)

[3 7]
